import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header/Header'
import HeroBanner from '@/components/HeroBanner/HeroBanner'
import Footer from '@/components/Footer/Footer'
import "react-big-calendar/lib/css/react-big-calendar.css";
import NavigationMenu from '@/components/Header/NavigationMenu'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={inter.className}>
        <NavigationMenu />
        <Header />
        <HeroBanner />
        {children}
        <Footer />
      </body>
    </html>
  )
}
